**Numpy Basics**

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [2]:
#initializing normal array in python
arr = [1,2,3,4,5]
print(arr)

[1, 2, 3, 4, 5]


In [3]:
#importing numpy library with its alias
import numpy as np
#creating array with numpy .array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#checking numpy version
print(np.__version__)

1.25.2


In [5]:
arr = np.array((1, 2, 3, 4, 5))

print(arr) 

[1 2 3 4 5]


In [6]:
#two dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) 


[[1 2 3]
 [4 5 6]]


In [7]:
print(arr.ndim)


2


In [8]:
lst=[1,23,4,5]
arr = np.array(lst)



In [9]:
type(arr)

numpy.ndarray

In [10]:
arr

array([ 1, 23,  4,  5])

In [11]:
arr[3]

5

In [12]:
a=90
#sin value of a
np.sin(a)
#exp value of a
np.exp(a)

1.2204032943178408e+39

In [13]:
arr = np.array([1,23,4,5,6,9,5,4,5,595,55,5515,55,52])
#sum of an array
np.sum(arr)
#mean of an array
np.mean(arr)
#max of an array
np.max(arr)
#min of an array
np.min(arr)

1

In [14]:
#finding standard deviation of an array
np.std(arr)

1412.0166790944136

In [15]:
#finding vaiance of an array
np.var(arr)

1993791.1020408163

In [38]:
arr1 = np.array([2,3,4,5,67])
np.concatenate((arr, arr1), axis=0, out=None, dtype=None, casting="same_kind")


array([   1,   23,    4,    5,    6,    9,    5,    4,    5,  595,   55,
       5515,   55,   52,    2,    3,    4,    5,   67])

In [49]:
ab = np.array([[1,2,3,49],[2,5,4,8]])


In [54]:
#get dimension
ab.shape


(2, 4)

In [52]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])


In [53]:
a



array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])